# Generated by Django 4.1.3 on 2022-11-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NYC_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=20)),
                ('street_name', models.CharField(max_length=20)),
                ('block_NO', models.CharField(max_length=20)),
                ('Lot_No', models.CharField(max_length=20)),
                ('Built_Year', models.CharField(max_length=20)),
                ('Building_class', models.CharField(max_length=20)),
                ('Owner', models.CharField(max_length=20)),
                ('State', models.CharField(default='NYC', max_length=20)),
            ],
            options={
                'db_table': 'NYC_data',
            },
        ),
    ]
